### ISSUE TITLE
Label Incomplete will not be removed

### ISSUE THREAD

**Issue by fk-bitsandlikes** [shyim/danger-php#605]
I created a pull request [github.com/shopware#2747](https://github.com/shopware/platform/pull/2747), there this code is used as action.

After creating the PR, the action labeled the PR as _Incomplete_ and created a post that Migration Test(s) are missing.
I had written the test, but it was in the wrong place. I quickly fixed that and pushed it.
After that, the action went through again, but this time successfully.
In the process, the post with the missing Migration Test(s) has been removed, but the _Incomplete_ label has remained.

As far as I can tell, in [.danger.php#L37](https://github.com/shyim/danger-php/blob/cd00c42c28b9e4e1c11d3c9eba9ccb3db7656984/.danger.php#L37) the label should be removed, which didn't happen.
Where exactly the problem lies, I have not been able to find out.
The remove function [AbstractPlatform.php#L42-L53](https://github.com/shyim/danger-php/blob/cd00c42c28b9e4e1c11d3c9eba9ccb3db7656984/src/Platform/AbstractPlatform.php#L42-L53) looks correct.

By the way:
The comment on missing migration test(s) was present 3 times, which is a bit irritating.
It would be desirable to either specify the path to the missing test (if feasible the better solution) or to remove duplicate messages (feasible by using array_unique, e.g. `array_unique($context->getFailures())` https://github.com/shyim/danger-php/blob/cd00c42c28b9e4e1c11d3c9eba9ccb3db7656984/src/Renderer/HTMLRenderer.php#L41-L43)

**Comment by shyim** [comment]
It is not a issue of this repo.

https://github.com/shopware/platform/blob/trunk/.danger.php#L312

It's just not removed inside platform repo. The removal is also not intended to be done automaically someone should review it as Incomplete can be set also by an human
