### ISSUE TITLE
Bug with docker image syntax when running in GitHub workflow

### ISSUE THREAD

**Issue by beberlei** [shyim/danger-php#846]
<img width="897" alt="Bildschirmfoto 2024-07-04 um 22 39 29" src="https://github.com/shyim/danger-php/assets/26936/6f76e0c3-832c-40aa-8d46-59b51e1444ed">

**Comment by shyim** [comment]
Can you try `@0.3.1`?

**Comment by beberlei** [comment]
That works, thank you!

**Comment by beberlei** [comment]
The old versions were doucmented here: https://github.com/shyim/danger-php/blob/main/docs/ci.md
